apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ibanking
spec:
  hard:
    pods: "6" 
    requests.cpu: "4" 
    requests.memory: 2Gi 
    limits.cpu: "4" 
    limits.memory: 4Gi 
