apiVersion: v1
kind: Namespace
metadata:
  name: wealthmgmt
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: wealthmgmt
spec:
  hard:
    pods: "4"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
