apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-compliance-operatorgroup
  namespace: openshift-compliance
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: compliance-operator
  namespace: openshift-compliance
spec:
  channel: stable
  installPlanApproval: Automatic
  name: compliance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
